// Code generated by tui generate. DO NOT EDIT.
// Source: agentui.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
)

type agentUI struct {
	t *Tui

	ta *tui.TextArea // 输入框组件实例（跨帧同一实例，经 inputView mount 渲染）

	// ── 以下字段仅主循环读写 ──
	follow   bool             // 贴底跟随：新内容到达时自动滚到底
	scrollY  int              // 非跟随态的滚动偏移
	spinN    int              // spinner 帧计数
	msgsRef  *tui.Ref         // 消息区滚动容器（滚动计算的参照）
	helpOpen *tui.State[bool] // 帮助面板（原生 modal）开关
}

func newAgentUI(t *Tui) *agentUI {
	a := &agentUI{t: t, follow: true, msgsRef: tui.NewRef(), helpOpen: tui.NewState(false)}
	a.ta = tui.NewTextArea(
		tui.WithTextAreaAutoFocus(true),
		// 不设 maxHeight：库的 TextArea 没有 scroll-to-cursor，
		// 内容超过钳制行数后光标行被裁掉、编辑全部发生在不可见处
		// （粘贴/超长输入"看起来死了"）。放开后输入框随内容生长，
		// 光标永远可见——与 tview 时代行为一致。
		tui.WithTextAreaTextStyle(mainStyle),
		tui.WithTextAreaElementOptions(
			tui.WithFlexGrow(1),
			tui.WithBackground(inputBg),
		),
		tui.WithTextAreaOnSubmit(t.submitInput),
	)
	return a
}

func (a *agentUI) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBackground(bgStyle),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithBackground(bgStyle),
		tui.WithScrollOffset(0, a.offsetY()),
	)
	a.msgsRef.Set(__tui_1)
	if a.t.bannerSetSnapshot() {
		for __idx_0, line := range a.t.bannerLinesSnapshot() {
			_ = __idx_0
			__tui_2 := tui.New(
				tui.WithText(line),
				tui.WithTruncate(true),
				tui.WithTextStyle(subStyle),
			)
			__tui_1.AddChild(__tui_2)
		}
	}
	for __idx_0, s := range a.t.segsSnapshot() {
		_ = __idx_0
		if s.kind == segMarkdown {
			__tui_3 := app.Mount(a, tui.MountKey(0, s.id), func() tui.Component {
				return tui.NewMarkdown(
					tui.WithMarkdownSource(s.text),
				)
			})
			__tui_1.AddChild(__tui_3)
		} else {
			__tui_4 := app.Mount(a, tui.MountKey(1, __idx_0), func() tui.Component {
				return newTextSegView(s.spans)
			})
			__tui_1.AddChild(__tui_4)
		}
	}
	__tui_0.AddChild(__tui_1)
	if !a.t.exiting.Load() {
		if a.t.todoTextSnapshot() != "" {
			for __idx_0, line := range a.t.todoLinesSnapshot() {
				_ = __idx_0
				__tui_5 := tui.New(
					tui.WithText(line),
					tui.WithTruncate(true),
					tui.WithTextStyle(todoLineStyle(line)),
				)
				__tui_0.AddChild(__tui_5)
			}
		}
		__tui_6 := tui.New(
			tui.WithText(a.noticeText()),
			tui.WithWidthPercent(100.00),
			tui.WithTextAlign(tui.TextAlignRight),
			tui.WithHeight(1),
			tui.WithTextStyle(a.noticeStyle()),
		)
		__tui_0.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithAlign(tui.AlignEnd),
		)
		__tui_8 := tui.New(
			tui.WithText(a.indicatorText()),
			tui.WithWidth(2),
			tui.WithHeight(1),
			tui.WithBackground(inputBg),
			tui.WithTextStyle(a.indicatorStyle()),
		)
		__tui_7.AddChild(__tui_8)
		__tui_9 := app.Mount(a, 2, func() tui.Component {
			return a.inputView(app)
		})
		__tui_7.AddChild(__tui_9)
		__tui_0.AddChild(__tui_7)
		__tui_10 := app.MountPersistent(a, 3, func() tui.Component {
			return tui.NewModal(
				tui.WithModalOpen(a.helpOpen),
				tui.WithModalBackdrop("dim"),
				tui.WithModalKeyMap(a.helpModalKeyMap()),
				tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
			)
		})
		__tui_11 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidth(60),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderTitle(" slash commands — ctrl+k 关闭 "),
			tui.WithPadding(1),
			tui.WithBackground(bgStyle),
		)
		for __idx_0, it := range a.t.helpItemsSnapshot() {
			_ = __idx_0
			__tui_12 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			)
			__tui_13 := tui.New(
				tui.WithText(it.cmd),
				tui.WithTruncate(true),
				tui.WithWidth(16),
				tui.WithTextStyle(mainStyle),
			)
			__tui_12.AddChild(__tui_13)
			__tui_14 := tui.New(
				tui.WithText(it.desc),
				tui.WithTruncate(true),
				tui.WithFlexGrow(1),
				tui.WithTextStyle(subStyle),
			)
			__tui_12.AddChild(__tui_14)
			__tui_11.AddChild(__tui_12)
		}
		__tui_10.AddChild(__tui_11)
		__tui_0.AddChild(__tui_10)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (a *agentUI) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*agentUI)
	if !ok {
		return
	}
	a.t = f.t
	a.ta = f.ta
	a.follow = f.follow
	a.scrollY = f.scrollY
	a.spinN = f.spinN
}

func (a *agentUI) UpdateProps(fresh tui.Component) {
	a.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*agentUI)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *agentUI) bindAppFields(app *tui.App) {
	if a.ta != nil {
		a.ta.BindApp(app)
	}
	if a.helpOpen != nil {
		a.helpOpen.BindApp(app)
	}
}

func (a *agentUI) BindApp(app *tui.App) {
	a.bindAppFields(app)
}

var _ tui.AppBinder = (*agentUI)(nil)
